### ISSUE TITLE
/admin/dashboard redirects to /login and admin user does not logged in

### ISSUE THREAD

**Issue by guillaumebriday** [pifaace/symfony-blog#65]

**Comment by guillaumebriday** [comment]
I tried to connect with the ID :

- admin
- password

And it does not work after running the fixtures

**Comment by pifaace** [comment]
Thanks for the report, I [fixed](https://github.com/pifaace/symfony-blog/commit/6d0655d1691231f27a79b4a98581653c4c8310d0) it
